import type { FastifyInstance } from 'fastify'; import { z } from 'zod'; import { pool,withTx } from '../db.js'; import { requireUser,type AuthedRequest } from '../types.js'; import { MockCardProvider } from '../services/providers.js'; import { audit } from '../utils/audit.js';
const cards=new MockCardProvider();
export async function cardRoutes(app:FastifyInstance){
 app.get('/cards',async(req,reply)=>{if(!requireUser(req,reply))return; const r=await pool.query(`SELECT id,account_id,card_type,network,last4,expiry_month,expiry_year,status,online_enabled,pos_enabled,atm_enabled,daily_limit,created_at FROM cards WHERE user_id=$1 ORDER BY created_at DESC`,[(req as AuthedRequest).user.id]); return {cards:r.rows}});
 app.post('/cards',async(req,reply)=>{if(!requireUser(req,reply))return; const b=z.object({accountId:z.string().uuid(),type:z.enum(['VIRTUAL','PHYSICAL']).default('VIRTUAL')}).parse(req.body); const u=(req as AuthedRequest).user; const result=await withTx(async client=>{const a=(await client.query(`SELECT id FROM accounts WHERE id=$1 AND user_id=$2 AND status='ACTIVE'`,[b.accountId,u.id])).rows[0];if(!a)throw Object.assign(new Error('ACCOUNT_NOT_FOUND'),{statusCode:404}); const issued=await cards.issue({userId:u.id,accountId:b.accountId,type:b.type}); const c=(await client.query(`INSERT INTO cards(user_id,account_id,issuer,issuer_reference,card_type,network,token_reference,last4,expiry_month,expiry_year,status) VALUES($1,$2,'mock',$3,$4,$5,$6,$7,$8,$9,'ACTIVE') RETURNING id,card_type,network,last4,expiry_month,expiry_year,status`,[u.id,b.accountId,issued.providerReference,b.type,issued.network,issued.tokenReference,issued.last4,issued.expiryMonth,issued.expiryYear])).rows[0]; await audit(client,{actorType:'USER',actorId:u.id,action:'CARD_ISSUED',resourceType:'CARD',resourceId:c.id,requestId:req.id}); return c}); return reply.code(201).send(result);
 });
 app.post('/cards/:id/freeze',async(req,reply)=>{return setStatus(req,reply,'FROZEN')});
 app.post('/cards/:id/unfreeze',async(req,reply)=>{return setStatus(req,reply,'ACTIVE')});
 app.patch('/cards/:id/controls',async(req,reply)=>{if(!requireUser(req,reply))return; const b=z.object({onlineEnabled:z.boolean().optional(),posEnabled:z.boolean().optional(),atmEnabled:z.boolean().optional(),dailyLimit:z.string().regex(/^\d+(\.\d{1,2})?$/).nullable().optional()}).parse(req.body); const u=(req as AuthedRequest).user; const r=await pool.query(`UPDATE cards SET online_enabled=COALESCE($1,online_enabled),pos_enabled=COALESCE($2,pos_enabled),atm_enabled=COALESCE($3,atm_enabled),daily_limit=COALESCE($4,daily_limit),updated_at=now() WHERE id=$5 AND user_id=$6 RETURNING id,status,online_enabled,pos_enabled,atm_enabled,daily_limit`,[b.onlineEnabled??null,b.posEnabled??null,b.atmEnabled??null,b.dailyLimit??null,(req.params as { id:string }).id,u.id]);if(!r.rows[0])return reply.code(404).send({error:'CARD_NOT_FOUND'});return r.rows[0]});
 app.get('/cards/:id/transactions',async(req,reply)=>{if(!requireUser(req,reply))return;const r=await pool.query(`SELECT ct.* FROM card_transactions ct JOIN cards c ON c.id=ct.card_id WHERE ct.card_id=$1 AND c.user_id=$2 ORDER BY ct.created_at DESC LIMIT 100`,[(req.params as { id:string }).id,(req as AuthedRequest).user.id]);return {transactions:r.rows}});
 async function setStatus(req:any,reply:any,status:'ACTIVE'|'FROZEN'){if(!requireUser(req,reply))return;const u=req.user;const result=await withTx(async client=>{const c=(await client.query(`SELECT * FROM cards WHERE id=$1 AND user_id=$2 FOR UPDATE`,[req.params.id,u.id])).rows[0];if(!c)return null;if(status==='FROZEN'&&c.status==='BLOCKED')throw Object.assign(new Error('CARD_BLOCKED'),{statusCode:409});await cards.setStatus(c.issuer_reference,status);const out=(await client.query(`UPDATE cards SET status=$1,updated_at=now() WHERE id=$2 RETURNING id,status`,[status,c.id])).rows[0];await audit(client,{actorType:'USER',actorId:u.id,action:status==='FROZEN'?'CARD_FROZEN':'CARD_UNFROZEN',resourceType:'CARD',resourceId:c.id,requestId:req.id});return out});if(!result)return reply.code(404).send({error:'CARD_NOT_FOUND'});return result;}
}
