import type { FastifyInstance } from 'fastify'; import { z } from 'zod';
import { withTx,pool } from '../db.js'; import { requireUser,type AuthedRequest } from '../types.js'; import { getBankProvider } from '../services/providers.js'; import { audit } from '../utils/audit.js';
const bank=getBankProvider();
const transferSchema=z.object({sourceAccountId:z.string().uuid(),beneficiaryId:z.string().uuid(),amount:z.string().regex(/^\d+(\.\d{1,2})?$/),currency:z.string().length(3).default('NGN'),description:z.string().max(140).optional()});
export async function transferRoutes(app:FastifyInstance){
 app.get('/banks',async(req,reply)=>{if(!requireUser(req,reply))return; if(!bank.listBanks)return reply.code(503).send({error:'BANKS_NOT_SUPPORTED'}); return {banks:await bank.listBanks()};});
 app.post('/transfers/name-enquiry',async(req,reply)=>{if(!requireUser(req,reply))return; const b=z.object({bankCode:z.string().min(3),accountNumber:z.string().min(6)}).parse(req.body); return bank.nameEnquiry(b.bankCode,b.accountNumber)});
 app.post('/transfers',async(req,reply)=>{if(!requireUser(req,reply))return; const u=(req as AuthedRequest).user; const key=String(req.headers['idempotency-key']??''); if(!key)return reply.code(400).send({error:'IDEMPOTENCY_KEY_REQUIRED'}); const b=transferSchema.parse(req.body);
  const result=await withTx(async client=>{
   const existing=await client.query(`SELECT response_body FROM idempotency_keys WHERE user_id=$1 AND endpoint=$2 AND key=$3 AND expires_at>now()`,[u.id,'/api/v1/transfers',key]); if(existing.rows[0]) return {existing:true,data:existing.rows[0].response_body};
   const acc=(await client.query(`SELECT * FROM accounts WHERE id=$1 AND user_id=$2 FOR UPDATE`,[b.sourceAccountId,u.id])).rows[0]; if(!acc) throw Object.assign(new Error('ACCOUNT_NOT_FOUND'),{statusCode:404});
   if(acc.status!=='ACTIVE')throw Object.assign(new Error('ACCOUNT_NOT_ACTIVE'),{statusCode:403});
   const ben=(await client.query(`SELECT * FROM beneficiaries WHERE id=$1 AND user_id=$2 AND status='ACTIVE'`,[b.beneficiaryId,u.id])).rows[0]; if(!ben)throw Object.assign(new Error('BENEFICIARY_NOT_FOUND'),{statusCode:404});
   if(acc.currency!==b.currency)throw Object.assign(new Error('CURRENCY_MISMATCH'),{statusCode:400});
   const amt=Number(b.amount); if(Number(acc.available_balance)<amt)throw Object.assign(new Error('INSUFFICIENT_FUNDS'),{statusCode:409});
   const tr=(await client.query(`INSERT INTO transfers(source_account_id,beneficiary_id,amount,currency,status,idempotency_key,description,provider) VALUES($1,$2,$3,$4,'PENDING_AUTH',$5,$6,$7) RETURNING id,amount,currency,status,created_at`,[acc.id,ben.id,b.amount,b.currency,key,b.description??null,bank.constructor.name])).rows[0];
   const response={...tr}; await client.query(`INSERT INTO idempotency_keys(user_id,key,endpoint,request_hash,response_code,response_body,expires_at) VALUES($1,$2,$3,encode(digest($4,'sha256'),'hex'),$5,$6,now()+interval '24 hours')`,[u.id,key,'/api/v1/transfers',JSON.stringify(b),201,response]);
   await audit(client,{actorType:'USER',actorId:u.id,action:'TRANSFER_CREATED',resourceType:'TRANSFER',resourceId:tr.id,requestId:req.id}); return {existing:false,data:response};
  });
  if(result.existing)return reply.send(result.data); return reply.code(201).send(result.data);
 });
 app.post('/transfers/:id/authorize',async(req,reply)=>{if(!requireUser(req,reply))return; const u=(req as AuthedRequest).user; const id=(req.params as any).id; const result=await withTx(async client=>{const t=(await client.query(`SELECT t.*,a.user_id,a.available_balance FROM transfers t JOIN accounts a ON a.id=t.source_account_id WHERE t.id=$1 AND a.user_id=$2 FOR UPDATE`,[id,u.id])).rows[0]; if(!t)return null; if(t.status!=='PENDING_AUTH')throw Object.assign(new Error('INVALID_TRANSFER_STATE'),{statusCode:409}); if(Number(t.available_balance)<Number(t.amount))throw Object.assign(new Error('INSUFFICIENT_FUNDS'),{statusCode:409}); await client.query(`UPDATE transfers SET status='AUTHORIZED',updated_at=now() WHERE id=$1`,[id]); await client.query(`UPDATE accounts SET available_balance=available_balance-$1,updated_at=now() WHERE id=$2`,[t.amount,t.source_account_id]); await client.query(`INSERT INTO outbox_events(event_type,aggregate_type,aggregate_id,payload,available_at) VALUES('TRANSFER_AUTHORIZED','TRANSFER',$1,$2,now())`,[id,JSON.stringify({transferId:id})]); await audit(client,{actorType:'USER',actorId:u.id,action:'TRANSFER_AUTHORIZED',resourceType:'TRANSFER',resourceId:id,requestId:req.id}); return {id,status:'AUTHORIZED'};}); if(!result)return reply.code(404).send({error:'TRANSFER_NOT_FOUND'}); return result});
 app.get('/transfers',async(req,reply)=>{if(!requireUser(req,reply))return; const q=req.query as any; const r=await pool.query(`SELECT t.id,t.amount,t.currency,t.status,t.provider_reference,t.description,t.created_at,b.account_name,b.bank_code,b.account_number FROM transfers t JOIN accounts a ON a.id=t.source_account_id LEFT JOIN beneficiaries b ON b.id=t.beneficiary_id WHERE a.user_id=$1 ORDER BY t.created_at DESC LIMIT $2`,[(req as AuthedRequest).user.id,Math.min(Number(q?.limit)||50,100)]); return {transfers:r.rows}});
 app.get('/transfers/:id',async(req,reply)=>{if(!requireUser(req,reply))return; const r=await pool.query(`SELECT t.* FROM transfers t JOIN accounts a ON a.id=t.source_account_id WHERE t.id=$1 AND a.user_id=$2`,[(req.params as any).id,(req as AuthedRequest).user.id]); if(!r.rows[0])return reply.code(404).send({error:'TRANSFER_NOT_FOUND'}); return r.rows[0]});
}
