const DEMO_KEY='vaultpay_demo_state_v2';
const seed={loggedIn:false,user:{firstName:'Kelvin',lastName:'Okafor',phone:'+234 801 234 5678',email:'kelvin@example.com'},kyc:'VERIFIED',balance:1284500,accountNumber:'10123456789',cards:[{last4:'4821',network:'VISA',exp:'08/29',status:'ACTIVE',online:true,pos:true,atm:true},{last4:'1937',network:'MASTERCARD',exp:'02/30',status:'FROZEN',online:true,pos:false,atm:true}],transactions:[{merchant:'Salary',category:'Income',amount:850000,type:'credit',date:'Today · 09:14',status:'COMPLETED'},{merchant:'MTN',category:'Airtime',amount:5000,type:'debit',date:'Today · 08:42',status:'COMPLETED'},{merchant:'Transfer to John',category:'Bank transfer',amount:50000,type:'debit',date:'Yesterday · 16:31',status:'COMPLETED'}],beneficiaries:[{name:'John Doe',bank:'Demo Bank',account:'0123456789'}],alerts:[]};
let state=load();
function load(){try{return JSON.parse(localStorage.getItem(DEMO_KEY))||structuredClone(seed)}catch{return structuredClone(seed)}}
function save(){localStorage.setItem(DEMO_KEY,JSON.stringify(state))}
function money(n){return '₦'+Number(n).toLocaleString('en-NG',{minimumFractionDigits:2,maximumFractionDigits:2})}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');clearTimeout(window._tt);window._tt=setTimeout(()=>el.classList.remove('show'),2600)}
function navItems(){return [['home','⌂','Home'],['payments','↗','Send'],['cards','▰','Cards'],['activity','◷','Activity'],['kyc','✓','KYC'],['security','🔒','Security']]}
function render(){if(!state.loggedIn){renderAuth();return}const app=document.getElementById('app');const tab=state.tab||'home';app.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand">Vault<span>Pay</span></div><div class="nav">${navItems().map(([id,icon,label])=>`<button class="${tab===id?'active':''}" onclick="setTab('${id}')">${icon} &nbsp;${label}</button>`).join('')}<button class="danger" onclick="logout()">↪ Sign out</button></div></aside><main class="content"><div class="topbar"><div><div class="eyebrow">Personal financial workspace</div><h1>${tabTitle(tab)}</h1></div><div class="profile"><span class="pill">${state.kyc==='VERIFIED'?'✓ KYC VERIFIED':'KYC '+state.kyc}</span><div class="avatar">${state.user.firstName[0]}${state.user.lastName[0]}</div></div></div>${page(tab)}</main></div><div class="mobilebar">${navItems().slice(0,5).map(([id,icon,label])=>`<button class="${tab===id?'active':''}" onclick="setTab('${id}')">${icon}<div>${label}</div></button>`).join('')}</div>`}
function tabTitle(t){return ({home:'Good evening, '+state.user.firstName,payments:'Send money',cards:'Your cards',activity:'Activity',kyc:'Identity verification',security:'Security center'})[t]||'VaultPay'}
function page(t){if(t==='payments')return payments();if(t==='cards')return cards();if(t==='activity')return activity();if(t==='kyc')return kyc();if(t==='security')return security();return home()}
function home(){return `<div class="grid"><div><section class="panel hero"><div class="muted">Available balance</div><div class="balance">${money(state.balance)}</div><div class="muted">VaultPay account · ${state.accountNumber}</div><div class="actions"><button class="primary" onclick="setTab('payments')">Send money</button><button class="secondary" onclick="setTab('cards')">Manage cards</button></div></section><section class="panel" style="margin-top:18px"><div style="display:flex;justify-content:space-between;align-items:center"><h2>Recent activity</h2><button class="secondary" onclick="setTab('activity')">View all</button></div>${state.transactions.slice(0,5).map(txRow).join('')}</section></div><div><section class="panel"><h2>Financial controls</h2><div class="stat-row"><span>KYC verification</span><b class="positive">Verified</b></div><div class="stat-row"><span>Transfer authentication</span><b>Step-up</b></div><div class="stat-row"><span>Card security</span><b>Protected</b></div><div class="stat-row"><span>Audit logging</span><b>Enabled</b></div></section><section class="panel" style="margin-top:18px"><h2>Quick actions</h2><div class="actions"><button class="secondary" onclick="setTab('kyc')">Identity</button><button class="secondary" onclick="setTab('security')">Security</button><button class="secondary" onclick="openStatements()">Statement</button></div></section></div></div>`}
function txRow(t){return `<div class="tx-row"><div class="tx-left"><b>${t.merchant}</b><small>${t.category} · ${t.date}</small></div><div style="text-align:right"><b class="${t.type==='credit'?'positive':'negative'}">${t.type==='credit'?'+':'−'}${money(t.amount)}</b><small style="display:block;color:#7f8ba5">${t.status}</small></div></div>`}
function payments(){return `<section class="panel" style="max-width:720px"><h2>Send to a bank account</h2><div class="form"><label>Bank</label><select id="bank"><option>Demo Bank · 000013</option><option>Partner Bank · 000001</option></select><label>Account number</label><input id="acct" inputmode="numeric" maxlength="10" placeholder="10-digit account number"><button class="secondary" onclick="verifyBeneficiary()">Verify account</button><div id="verified"></div><label>Amount</label><input id="amount" inputmode="decimal" placeholder="₦0.00"><label>Description</label><input id="desc" maxlength="100" placeholder="What is this payment for?"><button class="primary" onclick="reviewPayment()">Review payment</button><div class="notice">Demo mode: this transaction does not move real money. In production, VaultPay submits transfers through the licensed sponsor bank/PSP and waits for provider confirmation.</div></div></section>`}
function verifyBeneficiary(){const acct=document.getElementById('acct').value.replace(/\D/g,'');if(acct.length!==10){toast('Enter a 10-digit account number.');return}document.getElementById('verified').innerHTML='<div class="success">✓ DEMO BENEFICIARY · '+acct+'</div>';window.demoBen={name:'DEMO BENEFICIARY',account:acct,bank:'Demo Bank'};toast('Account verified.')}
function reviewPayment(){const a=Number((document.getElementById('amount').value||'').replace(/[^0-9.]/g,''));if(!window.demoBen){toast('Verify the beneficiary first.');return}if(!a||a<=0){toast('Enter a valid amount.');return}if(a>state.balance){toast('Insufficient demo balance.');return}showModal('Confirm transfer',`<div class="notice"><b>To</b><br>${window.demoBen.name}<br>${window.demoBen.bank} · ${window.demoBen.account}<br><br><b>Amount</b><br><span style="font-size:28px;font-weight:900">${money(a)}</span></div>`,()=>completeTransfer(a))}
function completeTransfer(a){state.balance-=a;state.transactions.unshift({merchant:'Transfer to '+window.demoBen.name,category:'Bank transfer',amount:a,type:'debit',date:'Just now',status:'COMPLETED'});state.beneficiaries.unshift(window.demoBen);save();window.demoBen=null;toast('Demo transfer completed.');render()}
function cards(){return `<section class="panel"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px"><h2>Your cards</h2><button class="primary" onclick="issueCard()">+ Virtual card</button></div><div class="card-grid">${state.cards.map((c,i)=>`<div class="bank-card ${i%2?'gold':''}"><div>${c.network} · VaultPay</div><div class="chip"></div><div class="card-number">•••• •••• •••• ${c.last4}</div><div class="card-foot"><span>EXP ${c.exp}</span><b>${c.status}</b></div><div class="actions"><button class="secondary" onclick="toggleCard(${i})">${c.status==='FROZEN'?'Unfreeze':'Freeze'}</button><button class="secondary" onclick="cardInfo(${i})">Controls</button></div></div>`).join('')}</div><div class="notice" style="margin-top:16px">For production, card PAN/CVV/PIN data must remain in the issuer/card environment. This app stores only display-safe references.</div></section>`}
function issueCard(){state.cards.push({last4:String(Math.floor(1000+Math.random()*9000)),network:'VISA',exp:'12/30',status:'ACTIVE',online:true,pos:true,atm:true});save();toast('Demo virtual card issued.');render()}
function toggleCard(i){state.cards[i].status=state.cards[i].status==='FROZEN'?'ACTIVE':'FROZEN';save();toast(state.cards[i].status==='FROZEN'?'Card frozen.':'Card unfrozen.');render()}
function cardInfo(i){const c=state.cards[i];showModal('Card controls',`<div class="stat-row"><span>Online payments</span><b>${c.online?'ON':'OFF'}</b></div><div class="stat-row"><span>POS</span><b>${c.pos?'ON':'OFF'}</b></div><div class="stat-row"><span>ATM</span><b>${c.atm?'ON':'OFF'}</b></div>`,null)}
function activity(){return `<section class="panel"><div style="display:flex;justify-content:space-between;align-items:center"><h2>All transactions</h2><button class="secondary" onclick="openStatements()">Statement</button></div>${state.transactions.map(txRow).join('')}</section>`}
function kyc(){return `<section class="panel" style="max-width:700px"><h2>Identity verification</h2><div class="kycstate"><div class="muted">Current status</div><div style="font-size:28px;font-weight:900;margin-top:6px">${state.kyc}</div></div>${state.kyc==='VERIFIED'?'<div class="success">✓ Identity verification is complete in this demo.</div>':'<button class="primary" onclick="completeKyc()">Start verification</button>'}<div class="notice" style="margin-top:16px">Production KYC will connect to an approved Nigerian identity/KYC provider and the sponsor bank’s onboarding rules. Real identity documents should be uploaded to secure storage, not browser localStorage.</div></section>`}
function completeKyc(){state.kyc='VERIFIED';save();toast('Demo KYC verified.');render()}
function security(){return `<div class="grid-2"><section class="panel"><h2>Security status</h2><div class="stat-row"><span>Two-factor authentication</span><b class="positive">Enabled</b></div><div class="stat-row"><span>Session protection</span><b class="positive">Active</b></div><div class="stat-row"><span>Transfer idempotency</span><b class="positive">Enabled</b></div><div class="stat-row"><span>Audit logging</span><b class="positive">Enabled</b></div></section><section class="panel"><h2>Safety actions</h2><div class="actions"><button class="danger" onclick="freezeAll()">Freeze all cards</button><button class="secondary" onclick="toast('All other sessions revoked in demo.')">Sign out all devices</button><button class="secondary" onclick="resetDemo()">Reset demo</button></div><p class="notice" style="margin-top:16px">These controls demonstrate the intended UX. Production authentication, device binding, secrets, cryptographic keys and privileged actions must be handled by the backend and regulated provider environment.</p></section></div>`}
function freezeAll(){state.cards.forEach(c=>c.status='FROZEN');save();toast('All demo cards frozen.');render()}
function openStatements(){const lines=state.transactions.map(t=>`${t.date} | ${t.merchant} | ${t.type==='credit'?'+':'-'}${money(t.amount)}`).join('\n');showModal('Statement',`<pre class="code" style="white-space:pre-wrap;line-height:1.7">VaultPay Demo Statement\nAccount: ${state.accountNumber}\nBalance: ${money(state.balance)}\n\n${lines}</pre>`,null)}
function showModal(title,body,onConfirm){const root=document.createElement('div');root.className='modal-wrap';root.innerHTML=`<div class="modal"><h2>${title}</h2>${body}<div class="modal-actions"><button class="secondary" onclick="this.closest('.modal-wrap').remove()">Close</button>${onConfirm?'<button class="primary" id="confirmBtn">Confirm</button>':''}</div></div>`;document.body.appendChild(root);if(onConfirm)root.querySelector('#confirmBtn').onclick=()=>{root.remove();onConfirm()}}
function renderAuth(){document.getElementById('app').innerHTML=`<div class="auth"><section class="auth-card"><div class="brand">Vault<span>Pay</span></div><div class="eyebrow">Secure personal finance</div><h1>Welcome back</h1><p class="muted">Open the customer app immediately in demo mode.</p><div class="form"><label>Phone or email</label><input id="login" value="demo@vaultpay.local"><label>Password</label><input id="password" type="password" value="DemoPassword123!"><button class="primary full" onclick="login()">Sign in</button><button class="secondary full" onclick="demoAccess()">Enter demo without login</button></div><p class="notice" style="margin-top:18px">This standalone build is a frontend demo. It does not move real money or collect real card credentials.</p></section></div>`}
function login(){state.loggedIn=true;state.user.firstName='Kelvin';save();toast('Signed in to VaultPay demo.');render()}
function demoAccess(){login()}
function logout(){state.loggedIn=false;save();render()}
function setTab(t){state.tab=t;save();render()}
function resetDemo(){state=structuredClone(seed);state.loggedIn=true;save();render();toast('Demo reset.')}
render();
