import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client'; import './style.css';
const API=import.meta.env.VITE_API_URL||'/api/v1';

type User={id:string;phone:string;email?:string;status:string;role?:string;first_name?:string;last_name?:string};
type Account={id:string;account_number?:string;currency:string;status:string;ledger_balance:string;available_balance:string;provider?:string;provider_metadata?:any};
type Card={id:string;card_type:string;network:string;last4:string;expiry_month:number;expiry_year:number;status:string;online_enabled:boolean;pos_enabled:boolean;atm_enabled:boolean;daily_limit?:string};
type Bank={code:string;name:string};

async function api(path:string,opts:RequestInit={},token?:string){const headers=new Headers(opts.headers);if(opts.body!==undefined)headers.set('Content-Type','application/json');if(token)headers.set('Authorization',`Bearer ${token}`);const r=await fetch(API+path,{...opts,headers,credentials:'include'});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||data.message||'REQUEST_FAILED');return data}

function App(){
 const [token,setToken]=useState<string|null>(localStorage.getItem('vp_token'));const [user,setUser]=useState<User|null>(null);const [accounts,setAccounts]=useState<Account[]>([]);const [cards,setCards]=useState<Card[]>([]);const [transfers,setTransfers]=useState<any[]>([]);const [kyc,setKyc]=useState<any>(null);const [tab,setTab]=useState('home');const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 const refresh=async(t=token)=>{if(!t){setLoading(false);return}try{const [u,a,c,tr,k]=await Promise.all([api('/users/me',{},t),api('/accounts',{},t),api('/cards',{},t),api('/transfers',{},t),api('/kyc',{},t)]);setUser(u);setAccounts(a.accounts);setCards(c.cards);setTransfers(tr.transfers);setKyc(k);setError('')}catch(e:any){setError(e.message);setToken(null);localStorage.removeItem('vp_token')}finally{setLoading(false)}};
 useEffect(()=>{refresh()},[]);
 if(loading)return <div className="center">Loading VaultPay…</div>;
 if(!token)return <Auth onLogin={t=>{localStorage.setItem('vp_token',t);setToken(t);refresh(t)}}/>;
 const account=accounts[0];
 return <div className="app"><aside><div className="brand">Vault<span>Pay</span></div><button className={tab==='home'?'active':''} onClick={()=>setTab('home')}>⌂ Home</button><button className={tab==='payments'?'active':''} onClick={()=>setTab('payments')}>↗ Payments</button><button className={tab==='funding'?'active':''} onClick={()=>setTab('funding')}>₦ Funding</button><button className={tab==='cards'?'active':''} onClick={()=>setTab('cards')}>▰ Cards</button><button className={tab==='kyc'?'active':''} onClick={()=>setTab('kyc')}>✓ Verification</button><button className={tab==='security'?'active':''} onClick={()=>setTab('security')}>🔒 Security</button>{user?.role!=='CUSTOMER'&&<button className={tab==='admin'?'active':''} onClick={()=>setTab('admin')}>⚙ Admin</button>}<button className="logout" onClick={async()=>{await api('/auth/logout',{method:'POST'},token??undefined).catch(()=>{});localStorage.removeItem('vp_token');setToken(null)}}>Sign out</button></aside><main><header><div><div className="eyebrow">Personal wallet</div><h1>{user?.first_name||'Welcome'} 👋</h1></div><div className="pill">{kyc?.status==='VERIFIED'?'KYC VERIFIED':'KYC '+(kyc?.status||'NOT_STARTED')}</div></header>{error&&<div className="error">{error}</div>}{tab==='home'&&<Home account={account} transfers={transfers} setTab={setTab} refresh={refresh} kyc={kyc}/>} {tab==='payments'&&<Payments token={token} account={account} onDone={()=>refresh()}/>} {tab==='funding'&&<Funding token={token} account={account} kyc={kyc} onDone={()=>refresh()}/>} {tab==='cards'&&<Cards token={token} cards={cards} account={account} onDone={()=>refresh()}/>} {tab==='kyc'&&<Kyc token={token} kyc={kyc} onDone={()=>refresh()}/>} {tab==='security'&&<Security/>} {tab==='admin'&&<Admin token={token}/>}</main></div>
}

function Auth({onLogin}:{onLogin:(t:string)=>void}){const [mode,setMode]=useState<'login'|'register'>('login');const [form,setForm]=useState<any>({});const [busy,setBusy]=useState(false);const [err,setErr]=useState('');const go=async()=>{setBusy(true);setErr('');try{const data=mode==='login'?await api('/auth/login',{method:'POST',body:JSON.stringify({login:form.login,password:form.password})}):await api('/auth/register',{method:'POST',body:JSON.stringify({phone:form.phone,email:form.email,password:form.password,firstName:form.firstName,lastName:form.lastName})});onLogin(data.accessToken)}catch(e:any){setErr(e.message)}finally{setBusy(false)}};return <div className="auth"><div className="authcard"><div className="brand">Vault<span>Pay</span></div><h1>{mode==='login'?'Welcome back':'Create your account'}</h1><p className="muted">Secure personal finance workspace.</p>{mode==='register'&&<><input placeholder="First name" onChange={e=>setForm({...form,firstName:e.target.value})}/><input placeholder="Last name" onChange={e=>setForm({...form,lastName:e.target.value})}/><input placeholder="Phone" onChange={e=>setForm({...form,phone:e.target.value})}/><input placeholder="Email" onChange={e=>setForm({...form,email:e.target.value})}/></>}{mode==='login'?<input placeholder="Phone or email" onChange={e=>setForm({...form,login:e.target.value})}/>:null}<input type="password" placeholder="Password" onChange={e=>setForm({...form,password:e.target.value})}/>{err&&<div className="error">{err}</div>}<button className="primary full" disabled={busy} onClick={go}>{busy?'Please wait…':mode==='login'?'Sign in':'Create account'}</button><button className="link" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?"Don't have an account? Register":"Already registered? Sign in"}</button></div></div>}

function Home({account,transfers,setTab,refresh,kyc}:{account?:Account;transfers:any[];setTab:(x:string)=>void;refresh:()=>void;kyc:any}){const openAccount=async()=>{try{await api('/accounts',{method:'POST'},localStorage.getItem('vp_token')||undefined);refresh()}catch(e:any){alert(e.message)}};return <><section className="hero"><div><div className="muted">Available balance</div><div className="balance">{account?`${account.currency} ${Number(account.available_balance).toLocaleString(undefined,{minimumFractionDigits:2})}`:'—'}</div><div className="muted">Account {account?.account_number||'not opened'}</div></div><div className="actions"><button className="primary" onClick={()=>setTab('payments')} disabled={!account}>Send money</button><button onClick={()=>setTab('cards')} disabled={!account}>Manage cards</button>{!account&&kyc?.status==='VERIFIED'&&<button onClick={openAccount}>Open NGN account</button>}</div></section><section className="grid2"><div className="panel"><h2>Recent activity</h2>{transfers.slice(0,6).map(t=><div className="row" key={t.id}><div><b>{t.account_name||'Bank transfer'}</b><small>{new Date(t.created_at).toLocaleString()}</small></div><div className="amount">- {t.currency} {Number(t.amount).toLocaleString(undefined,{minimumFractionDigits:2})}<small>{t.status}</small></div></div>)}{!transfers.length&&<div className="empty">No transfers yet.</div>}</div><div className="panel"><h2>Financial controls</h2><div className="stat"><span>KYC</span><b>{kyc?.status||'Required'}</b></div><div className="stat"><span>Funding account</span><b>{account?.account_number?'Ready':'Not set'}</b></div><div className="stat"><span>Card security</span><b>Enabled</b></div><div className="stat"><span>Transaction authentication</span><b>Step-up</b></div></div></section></>}

function Payments({token,account,onDone}:{token:string;account?:Account;onDone:()=>void}){const [banks,setBanks]=useState<Bank[]>([]);const [bankCode,setBankCode]=useState('');const [acct,setAcct]=useState('');const [name,setName]=useState('');const [amount,setAmount]=useState('');const [beneficiaryId,setBeneficiaryId]=useState('');const [message,setMessage]=useState('');useEffect(()=>{api('/banks',{},token).then(r=>{setBanks(r.banks);if(r.banks[0])setBankCode(r.banks[0].code)}).catch(e=>setMessage(e.message))},[token]);const enquiry=async()=>{try{const r=await api('/transfers/name-enquiry',{method:'POST',body:JSON.stringify({bankCode,accountNumber:acct})},token);setName(r.accountName);const b=await api('/beneficiaries',{method:'POST',body:JSON.stringify({bankCode,accountNumber:acct,accountName:r.accountName,providerReference:r.providerReference})},token);setBeneficiaryId(b.id);setMessage('Beneficiary verified.')}catch(e:any){setMessage(e.message)}};const send=async()=>{try{const r=await api('/transfers',{method:'POST',body:JSON.stringify({sourceAccountId:account?.id,beneficiaryId,amount,currency:'NGN',description:'VaultPay transfer'}),headers:{'Idempotency-Key':crypto.randomUUID()}},token);await api(`/transfers/${r.id}/authorize`,{method:'POST'},token);setMessage('Transfer accepted and queued. Provider status will update asynchronously.');onDone()}catch(e:any){setMessage(e.message)}};return <div className="panel narrow"><h2>Send money</h2><select value={bankCode} onChange={e=>setBankCode(e.target.value)}><option value="">Select bank</option>{banks.map(b=><option key={b.code} value={b.code}>{b.name} · {b.code}</option>)}</select><input placeholder="Account number" inputMode="numeric" value={acct} onChange={e=>setAcct(e.target.value)}/><button onClick={enquiry}>Verify beneficiary</button>{name&&<div className="verified">✓ {name}</div>}<input placeholder="Amount (NGN)" value={amount} onChange={e=>setAmount(e.target.value)}/><button className="primary" disabled={!beneficiaryId||!amount||!account} onClick={send}>Review & send</button>{message&&<div className="muted">{message}</div>}<p className="note">When configured, VaultPay sends the transfer through the licensed provider adapter and waits for an asynchronous provider result/webhook.</p></div>}

function Funding({token,account,kyc,onDone}:{token:string;account?:Account;kyc:any;onDone:()=>void}){const [isPermanent,setPermanent]=useState(true);const [bvn,setBvn]=useState('');const [nin,setNin]=useState('');const [result,setResult]=useState<any>(null);const go=async()=>{try{if(!account)await api('/accounts',{method:'POST'},token);const fresh=(await api('/accounts',{},token)).accounts[0];const r=await api(`/accounts/${fresh.id}/funding-instructions`,{method:'POST',body:JSON.stringify({isPermanent,bvn:bvn||undefined,nin:nin||undefined})},token);setResult(r);onDone()}catch(e:any){alert(e.message)}};return <div className="panel narrow"><h2>Fund your VaultPay account</h2>{!kyc||kyc.status!=='VERIFIED'?<div className="notice">Complete KYC first. The live provider flow requires approved customer verification.</div>:<><div className="stat"><span>Permanent account</span><b>{isPermanent?'YES':'NO'}</b></div><button onClick={()=>setPermanent(!isPermanent)}>{isPermanent?'Use temporary account':'Use permanent account'}</button>{isPermanent&&<><input placeholder="BVN (11 digits)" inputMode="numeric" maxLength={11} value={bvn} onChange={e=>setBvn(e.target.value.replace(/\D/g,''))}/><input placeholder="NIN (optional alternative)" value={nin} onChange={e=>setNin(e.target.value)}/></>}<button className="primary" onClick={go}>Create funding account</button>{result&&<div className="verified">✓ {result.bankName}<br/><b>{result.accountNumber}</b><br/><small>{result.isPermanent?'Permanent':'Temporary'} funding account</small></div>}<p className="note">Do not store BVN/NIN in browser storage. This form sends the value directly to the backend/provider and does not persist it in VaultPay's application database.</p></>}</div>}

function Cards({token,cards,account,onDone}:{token:string;cards:Card[];account?:Account;onDone:()=>void}){const issue=async()=>{try{await api('/cards',{method:'POST',body:JSON.stringify({accountId:account?.id,type:'VIRTUAL'})},token);onDone()}catch(e:any){alert(e.message)}};return <div className="panel"><div className="panelhead"><h2>Your cards</h2><button className="primary" onClick={issue} disabled={!account}>Issue virtual card</button></div><div className="cardgrid">{cards.map(c=><div className="bankcard" key={c.id}><div>{c.network} •••• {c.last4}</div><div className="chip"></div><div className="digits">•••• •••• •••• {c.last4}</div><div className="foot">EXP {String(c.expiry_month).padStart(2,'0')}/{String(c.expiry_year).slice(-2)} <span>{c.status}</span></div></div>)}{!cards.length&&<div className="empty">No cards yet.</div>}</div><p className="note">Card controls are connected to the VaultPay card-provider interface. The bundled MVP uses the mock issuer until a production card-issuer integration is contracted and enabled.</p></div>}
function Kyc({token,kyc,onDone}:{token:string;kyc:any;onDone:()=>void}){const [bvn,setBvn]=useState('');const [busy,setBusy]=useState(false);const start=async()=>{setBusy(true);try{const r=await api('/kyc',{method:'POST',body:JSON.stringify({bvn})},token);onDone();if(r?.metadata?.consentUrl)window.open(r.metadata.consentUrl,'_blank','noopener');}catch(e:any){alert(e.message)}finally{setBusy(false)}};return <div className="panel narrow"><h2>Identity verification</h2><div className="kycstate"><div>Status</div><strong>{kyc?.status||'NOT_STARTED'}</strong></div>{kyc?.metadata?.consentUrl&&kyc?.status!=='VERIFIED'&&<p><a href={kyc.metadata.consentUrl} target="_blank" rel="noreferrer">Continue BVN consent</a></p>}<input placeholder="BVN (11 digits)" inputMode="numeric" maxLength={11} value={bvn} onChange={e=>setBvn(e.target.value.replace(/\D/g,''))}/><button className="primary" onClick={start} disabled={busy||kyc?.status==='VERIFIED'||bvn.length!==11}>{busy?'Starting…':kyc?.status==='VERIFIED'?'Verified':'Start BVN verification'}</button><p className="note">The live BVN flow uses a hosted consent page. Completion is asynchronous and the backend updates the KYC state from the provider result.</p></div>}
function Security(){return <div className="panel"><h2>Security center</h2><div className="stat"><span>2-factor authentication</span><b>Ready</b></div><div className="stat"><span>Refresh sessions</span><b>Rotating</b></div><div className="stat"><span>Financial actions</span><b>Idempotent</b></div><div className="stat"><span>Audit trail</span><b>Enabled</b></div></div>}
function Admin({token}:{token:string}){const [logs,setLogs]=useState<any[]>([]);const [kyc,setKyc]=useState<any[]>([]);useEffect(()=>{Promise.all([api('/admin/audit-logs',{},token),api('/admin/kyc',{},token)]).then(([a,k])=>{setLogs(a.logs);setKyc(k.kyc)}).catch(()=>{})},[token]);return <div className='grid2'><div className='panel'><h2>KYC queue</h2>{kyc.map((x:any)=><div className='row' key={x.id}><div><b>{x.first_name} {x.last_name}</b><small>{x.email||x.phone}</small></div><div><b>{x.status}</b>{x.status!=='VERIFIED'&&<button onClick={async()=>{await api(`/admin/kyc/${x.user_id}/verify`,{method:'POST'},token);location.reload()}}>Verify</button>}</div></div>)}</div><div className='panel'><h2>Audit log</h2>{logs.slice(0,15).map((x:any)=><div className='row' key={x.id}><div><b>{x.action}</b><small>{x.actor_type}</small></div><small>{new Date(x.created_at).toLocaleString()}</small></div>)}</div></div>}

createRoot(document.getElementById('root')!).render(<App/>);
