FROM node:22-alpine AS build
WORKDIR /app
COPY . .
RUN npm install
RUN npm --workspace apps/api run build
RUN npm prune --omit=dev

FROM node:22-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/apps/api/package.json ./apps/api/package.json
COPY --from=build /app/apps/api/dist ./apps/api/dist
COPY --from=build /app/db ./db
COPY --from=build /app/scripts ./scripts
EXPOSE 4000
CMD ["node","apps/api/dist/server.js"]
